sudo: required
language: python
dist: xenial
python:
- '3.6'
services:
- docker
branches:
  except:
  - gh-pages
  - github_metadata
before_install:
- chmod +x ./build.sh
script:
- travis_wait ./build.sh -b plutosdr
before_deploy:
- curl https://github.com/lindell/github-release-cli/releases/download/0.5.0/github-releaser-travis -L --output github-releaser && chmod +x github-releaser
- export BODY=$(envsubst < ./CHANGELOG.md)
- export FILES=releases/*
- export RELEASE_NAME=$(echo "OSCIMP Buildroot v$TRAVIS_TAG" | envsubst)
deploy:
  - provider: script
    script: ./github-releaser -draft -verbose
    skip_cleanup: true
    on:
      branch: master
      tags: true
matrix:
  fast_finish: true
notifications:
  email: false
